### ISSUE TITLE
Support custom numbering schemes

### ISSUE THREAD

**Issue by sloria** [hlcfan/pokr#152]
It would be great if pokr supported custom numbering schemes. At the place that I work, we use 1-8 rather than the Fibonacci sequence.

**Comment by hlcfan** [comment]
@sloria Thanks for your feedback! 
I'll let you know when it's done.

**Comment by sloria** [comment]
Thanks!

**Comment by hlcfan** [comment]
If Pokrex provides with multi schemes, like "Fibonacci" and "1-8".etc, will that work?

**Comment by sloria** [comment]
@hlcfan Yes, that will work for us.

**Comment by hlcfan** [comment]
I'd like you to have a look before pushing this change to PROD.

![image](https://user-images.githubusercontent.com/1140383/30778871-f07780ac-a112-11e7-8d9f-797611d7fcd3.png)
![image](https://user-images.githubusercontent.com/1140383/30778872-f47e7b2e-a112-11e7-8822-8d93e382770a.png)

**Comment by sloria** [comment]
Looks good! Can you still select "?!" and "coffee" if you choose 1-8?

**Comment by hlcfan** [comment]
Sure 😅

**Comment by sloria** [comment]
Also, the button under "Point values" should read "0-8" if the numbering will start at 0. We only use 1-8, but it's fine if 0 is included; the button should just be consistent.

**Comment by hlcfan** [comment]
@sloria This has been on PROD, please check and lemme know if any issues.

**Comment by sloria** [comment]
Looks good to me! Thanks a lot.
