### ISSUE TITLE
Don't require authentication

### ISSUE THREAD

**Issue by sloria** [hlcfan/pokr#153]
It would be great if pokr could be used without having to register/log in--just create a new session and share the link with your teammates. This is one of the things I really like about https://www.pointingpoker.com.

**Comment by hlcfan** [comment]
Yea, I've been thinking about this for long 🤔 

To allow team/users to review the summary/results/some other statistics after grooming session, Pokrex needs user to signed in. 

I can think of a way to sort this out. For scrum master, she/he must be signed in, for participants, they don't need to. Therefore, scrum master can still review the summary after grooming session and rest of the team do not need to sign in. Do you think this works?

**Comment by sloria** [comment]
That would certainly be a big improvement. 👍 

It would still be nice if the scrum master didn't need to authenticate if they don't need to store the summary, etc, but that can be a future improvement.

**Comment by sloria** [comment]
Nice work!

**Comment by hlcfan** [comment]
Thanks!

Current implementation only has entry for participants to join without sign up or sign in, for moderators sign up or sign in is still required, I'll open an entry for all users to create or join a room as guest.
