### ISSUE TITLE
Update logo

### ISSUE THREAD

**Issue by sloria** [hlcfan/pokr#164]
The logo in the navbar is outdated (reads "Pokr").

<img width="97" alt="log in pokrex 2017-10-06 16-09-12" src="https://user-images.githubusercontent.com/2379650/31296548-b5be54ac-aab0-11e7-88a2-3876f3827c7a.png">

It should be updated with the new "Pokrex" logo for consistent branding:

<img width="147" alt="online planning poker pokrex 2017-10-06 16-10-00" src="https://user-images.githubusercontent.com/2379650/31296579-d0e0d89a-aab0-11e7-8f4e-0a3daa440a6c.png">

**Comment by hlcfan** [comment]
Fixed in https://github.com/hlcfan/pokr/commit/aeb09d1d1a345f4f2ee30340af3b725b1b2149cc

**Comment by hlcfan** [comment]
Thanks!

**Comment by sloria** [comment]
Thank you.

It might also make sense to rename this repo to pokrex. GitHub handles redirects for renamed repos anyway.
