### ISSUE TITLE
Remove confirmation on unload events

### ISSUE THREAD

**Issue by sloria** [hlcfan/pokr#173]
Whenever you try to try to edit or leave a room, you see a javascript confirmation popup:

<img width="995" alt="djangole grooming 2017-10-20 pokrex 2017-10-19 10-24-00" src="https://user-images.githubusercontent.com/2379650/31775863-cf5d371e-b4b7-11e7-9cf7-340c548cc027.png">

This is quite annoying because it interrupts user flow.

I propose removing it.

**Comment by hlcfan** [comment]
Sounds good, I'll propose a PR next week.
