### ISSUE TITLE
Responsiveness issue: Delete and add story buttons overlap on smaller screens

### ISSUE THREAD

**Issue by sloria** [hlcfan/pokr#178]
<img width="662" alt="create room pokrex 2017-12-01 10-47-04" src="https://user-images.githubusercontent.com/2379650/33490394-009a003e-d685-11e7-92bf-8167df4453de.png">

On the "Create room" page, the delete and add story buttons get mashed together on smaller screens.

**Comment by hlcfan** [comment]
Thanks  for mentioning this!

I'm been thinking refining the mobile version of Pokrex. Will submit a PR these days probably, based on the effort :-)
