### ISSUE TITLE
Moderators get lost after clicking "Edit Room"

### ISSUE THREAD

**Issue by sloria** [hlcfan/pokr#184]
Steps to reproduce:

1. Create a room and add a moderator
2. Click "Edit room"
3. Click "Submit"

Expected: No information is modified
Actual: Moderators are removed

**Comment by hlcfan** [comment]
Sorry for the late response, it's Chinese new year, good wishes to you.

I cannot reproduce this, made a short clip, is it right?

![ezgif-4-34a6d445fc](https://user-images.githubusercontent.com/1140383/36361070-13be6bfa-1564-11e8-921b-9a2b167a900e.gif)

**Comment by sloria** [comment]
No, that's a different issue. Here is what is happening:

![pokrex-bug](https://user-images.githubusercontent.com/2379650/36387041-cbe4ce44-1565-11e8-87f0-b9e96d4753c9.gif)

Notice that after I click "Edit room", the "Moderators" field is cleared.

**Comment by hlcfan** [comment]
Sorry, something wrong with the video to gif conversion, see the complete gif
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1140383/36575436-eb6a7aca-1885-11e8-9995-ec83a560c245.gif)

**Comment by sloria** [comment]
@hlcfan I can reproduce the bug on the latest versions of both Firefox (58) and Chrome (64).

Have you tried adding a Moderator that has a space in their name?

**Comment by hlcfan** [comment]
Just fixed this in https://github.com/hlcfan/pokr/commit/5f656da3275895a05c88392562017e14f9438b4c, I think #185 should be good as well. Thanks for your feedback!

**Comment by hlcfan** [comment]
@sloria Am I good to close it?

**Comment by sloria** [comment]
Just verified that this is fixed. Thanks!
