### ISSUE TITLE
[bug] Reordering stories doesn't work

### ISSUE THREAD

**Issue by sloria** [hlcfan/pokr#185]
On the "Edit" page, stories cannot be re-ordered.

<img src="https://user-images.githubusercontent.com/2379650/36564137-4d2ca798-17ea-11e8-8d2f-0d3f292aa4f2.gif" width="200" />

**Comment by hlcfan** [comment]
Thanks for your feedback!

Weird,,,I cannot reproduce this from my side with FF 58.0.1 (64-bit). Which version are you using?

**Comment by sloria** [comment]
I was able to reproduce this on the latest versions of Firefox (58) and Chrome (64).

**Comment by sloria** [comment]
Looks like this is fixed now. Thanks!
