### ISSUE TITLE
Moderator input broken after validation error

### ISSUE THREAD

**Issue by sloria** [hlcfan/pokr#200]
## Steps

* Click "Create room"
* Enter a user's name into the "Moderator" input. Don't fill in anything else because we want validation to fail.
* Click "Submit"

## Expected

Validation fails for room "Name" and "Stories", but the moderator input retains previous input.

## Actual

Validation fails, and the moderators' PKs are displayed in the input. Autocomplete no longer works.

**Comment by hlcfan** [comment]
@sloria Thanks for creating the issue, I'll fix it in coming days.

BTW, are you seeing any network issue while using pokrex, like cannot "vote" or "flip"?

**Comment by sloria** [comment]
I don't see any issues with voting or flipping.

**Comment by hlcfan** [comment]
OK, cool. It should be the company network issue then, thanks.

**Comment by hlcfan** [comment]
I decided to revert the changes, as local storage may break on IE10, will have another commit.

**Comment by hlcfan** [comment]
Fixed in https://github.com/hlcfan/pokr/commit/7c72eea919c5aa74a0c7aa50fa29318e869e6c3e and https://github.com/hlcfan/pokr/commit/ed7558a393d9c4bda99ee72a36812c314fed5776.
